/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-10-01 11:30:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import de.uniwue.apps.jm1.User;
import de.uniwue.apps.jm1.Item;
import de.uniwue.apps.jm1.Main;
import de.uniwue.apps.jm1.Buchung;
import java.text.SimpleDateFormat;
import java.util.List;
import java.text.DecimalFormat;

public final class admin_005fuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("de.uniwue.apps.jm1.Buchung");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.User");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.Item");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.Main");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User user = (User) session.getAttribute("user");
if (user == null || !user.isAdmin()) {
    response.sendRedirect("index.jsp");
    return;
}

user = User.getUserbyUID("" + user.getUid());
session.setAttribute("user", user);

// User to display parameter handling
String uid = null;
try {
    uid = "" + Integer.parseInt(request.getParameter("uid"));
} catch(Exception e) {
    // uid bleibt null
}
User userAnzeigen = User.getUserbyUID(uid);


String buchungsverlauf = null;
try {
	buchungsverlauf = "" + Integer.parseInt(request.getParameter("buchungsverlauf"));
} catch(Exception e) {
	// uid bleibt null
}

// Pagination für Buchungsverlauf - 50 pro Seite
int buchungsPage = 1;
int buchungsPerPage = 50;
try {
    String pageParam = request.getParameter("buchungsPage");
    if (pageParam != null) {
        buchungsPage = Integer.parseInt(pageParam);
        if (buchungsPage < 1) buchungsPage = 1;
    }
} catch (NumberFormatException e) {
    buchungsPage = 1;
}

// Pagination für Benutzer-Verlauf - 10 pro Seite  
int userPage = 1;
int userBuchungsPerPage = 10;
try {
    String pageParam = request.getParameter("userPage");
    if (pageParam != null) {
        userPage = Integer.parseInt(pageParam);
        if (userPage < 1) userPage = 1;
    }
} catch (NumberFormatException e) {
    userPage = 1;
}

// Formatierungen
DecimalFormat euroFormat = new DecimalFormat("#,##0.00 €");
SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm");
String adminGuthaben = euroFormat.format(user.getGuthaben() / 100.0);
String userGuthaben = userAnzeigen != null ? euroFormat.format(userAnzeigen.getGuthaben() / 100.0) : null;

List<User> myUsers = User.getUser();

      out.write("\r\n");
      out.write("<html lang=\"de\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Benutzerverwaltung - WueKaStL</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/admin.css\">\r\n");
      out.write("    <script src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("      <div class=\"header\">\r\n");
      out.write("        <div class=\"user-info-header\">\r\n");
      out.write("            <div class=\"user-name-header\">");
      out.print( user.getVorname() );
      out.write(' ');
      out.print( user.getNachname() );
      out.write("</div>\r\n");
      out.write("            <div class=\"saldo\">");
      out.print( adminGuthaben );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write(" <a class=\"logo\" href=\"index.jsp\" >WueKaStL</a>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"index.jsp\" class=\"btn  btn-danger\" >zur Startseite</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Hauptbereich -->\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <h2 class=\"main-title\">Benutzer und Buchungen</h2>\r\n");
      out.write("        ");
 if(userAnzeigen == null && buchungsverlauf == null) { 
      out.write("\r\n");
      out.write("        <!-- Navigation Buttons -->\r\n");
      out.write("        <div class=\"navigation\">\r\n");
      out.write("            <button id=\"neuer-Benutzer\" class=\"btn btn-auswahl\">\r\n");
      out.write("                Neuer Benutzer\r\n");
      out.write("            </button>\r\n");
      out.write("			<button id=\"Gruppenbuchung\" class=\"btn btn-auswahl\">\r\n");
      out.write("				Gruppenbuchung\r\n");
      out.write("			</button>\r\n");
      out.write("			<a href=\"admin_user.jsp?buchungsverlauf=1\" id=\"Verlauf\" class=\"btn btn-auswahl\">\r\n");
      out.write("				Buchungsverlauf\r\n");
      out.write("			</a>\r\n");
      out.write("        </div>\r\n");
      out.write("		<div class=\"user-navigation\">\r\n");
      out.write("		<div id=\"user-list-section\" class=\"list-container\">\r\n");
      out.write("        <div class=\"list-header\">\r\n");
      out.write("            <h3>Benutzer auswählen</h3>\r\n");
      out.write("            <div class=\"search\">\r\n");
      out.write("                <input type=\"text\" id=\"user-search-input\" placeholder=\"Name suchen...\" class=\"search-input\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("		<!-- User Grid -->\r\n");
      out.write("        <div class=\"grid\" id=\"user-grid\">\r\n");
      out.write("            ");
 for(User u : myUsers) {
                String statusClass = u.isAktiv() ? "active" : "inactive";
                String adminBadge = u.getStatus().equals("admin") ? "<span class='admin-badge'>Admin</span>" : "";
                String guthaben = euroFormat.format(u.getGuthaben() / 100.0);
                User.aktualisiereGuthaben(u);
            
      out.write("\r\n");
      out.write("            <div class=\"card\" data-uid=\"");
      out.print( u.getUid() );
      out.write("\">\r\n");
      out.write("            	<div class=\"name\" ");
if(u.isAdmin()){
      out.write(" style=\"font-weight: 800;\" ");
}
      out.write('>');
      out.print( u.getVorname() );
      out.write(' ');
      out.print( u.getNachname() );
      out.write("</div>\r\n");
      out.write("            	\r\n");
      out.write("                <div class=\"actions\">\r\n");
      out.write("                	<div class=\"info\">\r\n");
      out.write("               	 		<a class=\"");
if(u.getGuthaben() >= 0) { 
      out.write("positive");
 } else { 
      out.write("negative");
 } 
      out.write('"');
      out.write('>');
      out.print( guthaben );
      out.write("</a>\r\n");
      out.write("               	 		<div class=\"status\">\r\n");
      out.write("                  	    <div class=\"badge ");
      out.print( statusClass );
      out.write("\"> </div>\r\n");
      out.write("                 	    <div class=\"role\">");
      out.print( u.getStatus() );
      out.write(" </div>\r\n");
      out.write("                		</div>\r\n");
      out.write("                	</div>\r\n");
      out.write("              	  	<div class=\"form-actions\">\r\n");
      out.write("                    	<a href=\"admin_user.jsp?uid=");
      out.print( u.getUid() );
      out.write("\" class=\"btn btn-edit edit\">\r\n");
      out.write("                        Bearbeiten\r\n");
      out.write("                    	</a>\r\n");
      out.write("						<a  href=\"#\" class=\"btn btn-edit select\" style=\"display: none;\">\r\n");
      out.write("						Auswählen\r\n");
      out.write("						</a>\r\n");
      out.write("                	</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Gruppenbuchung -->\r\n");
      out.write("		<div id=\"gruppenbuchung-section\" class=\"list-container\" style=\"display: none; max-width: 400px;\">\r\n");
      out.write("			<div class=\"list-header\">\r\n");
      out.write("				<h3>Gruppenbuchung</h3>\r\n");
      out.write("				<button class=\"btn btn-close\">✕</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<form method=\"POST\" action=\"buchungen\" class=\"admin-form buchungs-form\">\r\n");
      out.write("				\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label>Betrag (€)</label>\r\n");
      out.write("                                <input name=\"betrag\" type=\"number\" step=\"0.01\" placeholder=\"0,00\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label>Kommentar</label>\r\n");
      out.write("                                <textarea name=\"kommentar\" rows=\"3\" placeholder=\"Grund für die Buchung...\"></textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"inputs\">\r\n");
      out.write("							</div>\r\n");
      out.write("                            <div class=\"buchung-actions\">\r\n");
      out.write("                                <button  type=\"submit\" name=\"method\" value=\"aufbuchen\" class=\"btn btn-success\">\r\n");
      out.write("                                    Aufbuchen\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button  type=\"submit\" name=\"method\" value=\"abbuchen\" class=\"btn btn-danger\">\r\n");
      out.write("                                    Abbuchen\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("        <div  id=\"new-user-section\" class=\"list-container \" style=\"display: none; max-width: 400px;  \"> \r\n");
      out.write("                    <div class=\"list-header\">\r\n");
      out.write("                        <h3>Neuen Benutzer erstellen</h3>\r\n");
      out.write("                        <button class=\"btn btn-close\">✕</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <form id=\"new-user-form\" method=\"POST\" action=\"benutzer\" class=\"admin-form\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"new-vorname\">Vorname *</label>\r\n");
      out.write("                            <input type=\"text\" id=\"new-vorname\" name=\"vorname\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"new-nachname\">Nachname *</label>\r\n");
      out.write("                            <input type=\"text\" id=\"new-nachname\" name=\"nachname\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"new-startguthaben\">Startguthaben</label>\r\n");
      out.write("							<input type=\"text\" id=\"new-startguthaben\" name=\"guthaben\" required>	\r\n");
      out.write("						</div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"new-status\">Status</label>\r\n");
      out.write("                            <select id=\"new-status\" name=\"status\" required>\r\n");
      out.write("                                <option value=\"Mitarbeiter\">Mitarbeiter</option>\r\n");
      out.write("                                <option value=\"Auszubildender\">Auszubildender</option>\r\n");
      out.write("                                <option value=\"Praktikant\">Praktikant</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("					<label for=\"new-status\">Admin</label>\r\n");
      out.write("					<select id=\"new-status\" name=\"admin\" required>\r\n");
      out.write("					<option value=\"nein\">nein</option>\r\n");
      out.write("					<option value=\"ja\">ja</option>\r\n");
      out.write("					</select>\r\n");
      out.write("					</div>						\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"new-pin\">PIN *</label>\r\n");
      out.write("                            <input type=\"password\" id=\"new-pin\" name=\"pin\" minlength=\"4\" maxlength=\"10\" placeholder=\"Mindestens 4 Zeichen\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-actions\">\r\n");
      out.write("                            <button type=\"submit\" name=\"method\" value=\"neuer-Benutzer\" class=\"btn btn-edit\">\r\n");
      out.write("                                Benutzer erstellen\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("				</div>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("		");
 if(userAnzeigen != null || buchungsverlauf != null) { 
      out.write("\r\n");
      out.write("		<!-- Navigation Buttons -->\r\n");
      out.write("			<div class=\"navigation\">\r\n");
      out.write("            <a href=\"admin_user.jsp\" class=\"btn btn-auswahl\"><i class=\"arrow left\"></i>  Zurück</a>\r\n");
      out.write("        </div>\r\n");
      out.write("		\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("		<!-- Buchungsverlauf -->\r\n");
      out.write("		");
 if(buchungsverlauf != null) { 
      out.write("\r\n");
      out.write("		<div class=\"verlauf-section\">\r\n");
      out.write("		            ");

                    java.util.List<Buchung> alleBuchungen = Buchung.getAllBuchungen();
                    alleBuchungen.sort((b1, b2) -> b2.getDatum().compareTo(b1.getDatum()));
                    
                    // Pagination für Buchungsverlauf
                    int totalBuchungen = alleBuchungen.size();
                    int totalBuchungsPages = (int) Math.ceil((double) totalBuchungen / buchungsPerPage);
                    
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Pagination für Buchungsverlauf -->\r\n");
      out.write("                    ");
 if (totalBuchungsPages > 1) { 
      out.write("\r\n");
      out.write("                    <div class=\"pagination\">\r\n");
      out.write("                        <div class=\"pagination-controls\">\r\n");
      out.write("                            <!-- Seitenzahlen -->\r\n");
      out.write("                            <div class=\"page-numbers\">\r\n");
      out.write("                                ");
 
                                int startPage = Math.max(1, buchungsPage - 1);
                                int endPage = Math.min(totalBuchungsPages, buchungsPage + 1);
                                
                                // Erste Seite falls nicht sichtbar
                                if (startPage > 1) { 
      out.write("\r\n");
      out.write("                                    <a href=\"admin_user.jsp?buchungsverlauf=1&buchungsPage=1\" class=\"page-number\">1</a>\r\n");
      out.write("                                    ");
 if (startPage > 2) { 
      out.write("\r\n");
      out.write("                                        <span class=\"page-dots\">...</span>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                ");
 }
                                
                                // Sichtbare Seitenzahlen
                                for (int i = startPage; i <= endPage; i++) { 
      out.write("\r\n");
      out.write("                                    ");
 if (i == buchungsPage) { 
      out.write("\r\n");
      out.write("                                        <span class=\"page-number active\">");
      out.print( i );
      out.write("</span>\r\n");
      out.write("                                    ");
 } else { 
      out.write("\r\n");
      out.write("                                        <a href=\"admin_user.jsp?buchungsverlauf=1&buchungsPage=");
      out.print( i );
      out.write("\" class=\"page-number\">");
      out.print( i );
      out.write("</a>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                ");
 }
                                
                                // Letzte Seite falls nicht sichtbar
                                if (endPage < totalBuchungsPages) { 
      out.write("\r\n");
      out.write("                                    ");
 if (endPage < totalBuchungsPages - 1) { 
      out.write("\r\n");
      out.write("                                        <span class=\"page-dots\">...</span>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    <a href=\"admin_user.jsp?buchungsverlauf=1&buchungsPage=");
      out.print( totalBuchungsPages );
      out.write("\" class=\"page-number\">");
      out.print( totalBuchungsPages );
      out.write("</a>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("                    <div class=\"verlauf-table-container\">\r\n");
      out.write("                        <table class=\"verlauf-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>Datum</th>            \r\n");
      out.write("									<th>#</th>\r\n");
      out.write("                                    <th>Benutzer</th>\r\n");
      out.write("                                    <th>Summe</th>\r\n");
      out.write("                                    <th>Kommentar</th>\r\n");
      out.write("                                    <th>Inhalt</th>\r\n");
      out.write("                                    <th></th>\r\n");
      out.write("                                    <th></th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                ");
 
                                // Berechnung der aktuellen Seite für Tabelle
                                int startIndex = (buchungsPage - 1) * buchungsPerPage;
                                int endIndex = Math.min(startIndex + buchungsPerPage, totalBuchungen);
                                
                                java.util.List<Buchung> buchungen = alleBuchungen.subList(startIndex, endIndex);
                                
                                for(Buchung buchung : buchungen) {
                                    String betrag = euroFormat.format(buchung.getSumme() / 100.0);
                                    String itemlist = Buchung.itemlistToString(buchung);
                                    String datum = dateFormat.format(buchung.getDatum());
									String buchungstyp = buchung.getBt().toString().toLowerCase();
									String vorname = User.getUserbyUID(Integer.toString(buchung.getUserID())).getVorname();
									String nachname = User.getUserbyUID(Integer.toString(buchung.getUserID())).getNachname();
                                    
                                
      out.write("\r\n");
      out.write("                                    <tr class=\"");
      out.print( buchungstyp );
      out.write("\">\r\n");
      out.write("                                        <td>");
      out.print( datum );
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print( buchung.getUid() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( vorname );
      out.write(' ');
      out.print( nachname );
      out.write("</td>\r\n");
      out.write("                                        <td class=\"betrag\">");
      out.print( betrag );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( buchung.getKommentar() != null ? buchung.getKommentar() : "-" );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( itemlist != null && !itemlist.trim().isEmpty() ? itemlist : "-" );
      out.write("</td>\r\n");
      out.write("                                        ");
 if(buchungstyp.equals("striche")) { 
      out.write("\r\n");
      out.write("                                        <td>\r\n");
      out.write("   											<form action=\"buchungen\" method=\"post\">\r\n");
      out.write("      										<input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print( buchung.getUserID());
      out.write("\">\r\n");
      out.write("     								   		<input type=\"hidden\" name=\"buchungID\" value=\"");
      out.print( buchung.getUid() );
      out.write("\">\r\n");
      out.write("      										<button type=\"submit\" name=\"method\" value=\"bearbeitenBuchung\" class=\"btn btn-edit \">Bearbeiten</button>\r\n");
      out.write("    										</form>\r\n");
      out.write("										</td>\r\n");
      out.write("										");
 } else { 
      out.write("\r\n");
      out.write("										<td>-</td>\r\n");
      out.write("										");
 } 
      out.write("\r\n");
      out.write("										<td>\r\n");
      out.write("  											<form action=\"buchungen\" method=\"post\">\r\n");
      out.write("     										<input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print(buchung.getUserID());
      out.write("\">\r\n");
      out.write("     										<input type=\"hidden\" name=\"buchungID\" value=\"");
      out.print( buchung.getUid() );
      out.write("\">\r\n");
      out.write("       										<button type=\"submit\" name=\"method\" value=\"loescheBuchung\" class=\"btn btn-danger\">Löschen</button>\r\n");
      out.write("   											</form>\r\n");
      out.write("										</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                          	</tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("        <!-- Anzeige Section -->\r\n");
      out.write("        <div class=\"Anzeige\">\r\n");
      out.write("            ");
 if(userAnzeigen != null) { 
      out.write("\r\n");
      out.write("                <section class=\"benutzer-einstellungen\">\r\n");
      out.write("                    <!-- User Info -->\r\n");
      out.write("                    <div class=\"user-info-section\">\r\n");
      out.write("                        <div class=\"user-header\">\r\n");
      out.write("                            <h3>");
      out.print( userAnzeigen.getVorname() );
      out.write(' ');
      out.print( userAnzeigen.getNachname() );
      out.write("</h3>\r\n");
      out.write("                            <div class=\"user-status ");
      out.print( userAnzeigen.isAktiv() ? "active" : "inactive" );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( userAnzeigen.isAktiv() ? "Aktiv" : "Inaktiv" );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"user-details\">\r\n");
      out.write("                            <p><strong>Status:</strong> ");
      out.print( userAnzeigen.getStatus() );
      out.write("</p>\r\n");
      out.write("                            <p><strong>Guthaben:</strong> <span class=\"balance\">");
      out.print( userGuthaben );
      out.write("</span></p>\r\n");
      out.write("                            <p><strong>Admin:</strong> ");
      out.print( userAnzeigen.isAdmin() ? "Ja" : "Nein" );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Aktivierung/Deaktivierung -->\r\n");
      out.write("                        ");
 if(!userAnzeigen.isAdmin()) { 
      out.write("\r\n");
      out.write("                            <form method=\"POST\" action=\"benutzer\" class=\"status-form\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print(userAnzeigen.getUid());
      out.write("\">\r\n");
      out.write("                                ");
 if(userAnzeigen.isAktiv()) { 
      out.write("\r\n");
      out.write("                                    <button type=\"submit\" name=\"method\" value=\"deaktivieren\" class=\"btn  btn-danger\">\r\n");
      out.write("                                        Deaktivieren\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    <button type=\"submit\" name=\"method\" value=\"aktivieren\" class=\"btn btn-success\">\r\n");
      out.write("                                        Aktivieren\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </form>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- Name ändern -->\r\n");
      out.write("                        <div class=\"name-bearbeiten\">\r\n");
      out.write("                            <h4>Name ändern</h4>\r\n");
      out.write("                            <form method=\"POST\" action=\"benutzer\" class=\"admin-form\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print(userAnzeigen.getUid());
      out.write("\">\r\n");
      out.write("                                <div class=\"form-row\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label>Vorname</label>\r\n");
      out.write("                                        <input name=\"vorname\" placeholder=\"");
      out.print( userAnzeigen.getVorname() );
      out.write("\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label>Nachname</label>\r\n");
      out.write("                                        <input name=\"nachname\" placeholder=\"");
      out.print( userAnzeigen.getNachname() );
      out.write("\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"submit\" name=\"method\" value=\"name-change\" class=\"btn btn-edit\">Name ändern</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Status ändern -->\r\n");
      out.write("                        ");
 if(!userAnzeigen.isAdmin()) { 
      out.write("\r\n");
      out.write("                            <div class=\"status-bearbeiten\">\r\n");
      out.write("                                <h4>Status ändern</h4>\r\n");
      out.write("                                <form method=\"POST\" action=\"benutzer\" class=\"admin-form\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print(userAnzeigen.getUid());
      out.write("\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <select name=\"status\" required>\r\n");
      out.write("                                            <option value=\"Mitarbeiter\" ");
      out.print( "Mitarbeiter".equals(userAnzeigen.getStatus()) ? "selected" : "" );
      out.write(">Mitarbeiter</option>\r\n");
      out.write("                                            <option value=\"Azubi\" ");
      out.print( "Azubi".equals(userAnzeigen.getStatus()) ? "selected" : "" );
      out.write(">Azubi</option>\r\n");
      out.write("                                            <option value=\"Praktikant\" ");
      out.print( "Praktikant".equals(userAnzeigen.getStatus()) ? "selected" : "" );
      out.write(">Praktikant</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                        <button type=\"submit\" name=\"method\" value=\"status-change\" class=\"btn btn-edit\">Status ändern</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- PIN ändern -->\r\n");
      out.write("                        <div class=\"neuer-pin\">\r\n");
      out.write("                            <h4>PIN ändern</h4>\r\n");
      out.write("                            <form method=\"POST\" action=\"benutzer\" class=\"admin-form\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print(userAnzeigen.getUid());
      out.write("\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input name=\"pin\" type=\"password\" placeholder=\"Neue PIN\" minlength=\"4\" maxlength=\"10\" class=\"pin-eingabe\"");
 if(userAnzeigen.isAdmin()) { 
      out.write(" required ");
 } 
      out.write(">\r\n");
      out.write("                                    <button type=\"submit\" name=\"method\" value=\"pin-change\" class=\"btn btn-edit\">PIN ändern</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Buchung Section -->\r\n");
      out.write("                    <div class=\"buchung-section\">\r\n");
      out.write("                        <h4>Guthaben verwalten</h4>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Buchungsformular -->\r\n");
      out.write("                        <form method=\"POST\" action=\"buchungen\" class=\"admin-form buchungs-form\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print( userAnzeigen.getUid() );
      out.write("\">\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"current-balance\">\r\n");
      out.write("                                <strong>Aktuelles Guthaben: ");
      out.print( userGuthaben );
      out.write("</strong>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label>Betrag (€)</label>\r\n");
      out.write("                                <input name=\"betrag\" type=\"number\" step=\"0.01\" placeholder=\"0,00\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label>Kommentar</label>\r\n");
      out.write("                                <textarea name=\"kommentar\" rows=\"3\" placeholder=\"Grund für die Buchung...\"></textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"buchung-actions\">\r\n");
      out.write("                                <button type=\"submit\" name=\"method\" value=\"aufbuchen\" class=\"btn btn-success\">\r\n");
      out.write("                                    Aufbuchen\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button type=\"submit\" name=\"method\" value=\"abbuchen\" class=\"btn btn-danger\">\r\n");
      out.write("                                    Abbuchen\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <!-- Verlauf -->\r\n");
      out.write("                <div class=\"verlauf-section\">\r\n");
      out.write("                    ");

                    java.util.List<Buchung> alleUserBuchungen = Buchung.getBuLi(userAnzeigen);
                    alleUserBuchungen.sort((b1, b2) -> b2.getDatum().compareTo(b1.getDatum()));
                    
                    // Pagination für Benutzer-Verlauf
                    int totalUserBuchungen = alleUserBuchungen.size();
                    int totalUserPages = (int) Math.ceil((double) totalUserBuchungen / userBuchungsPerPage);
                    
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Pagination für Benutzer-Verlauf -->\r\n");
      out.write("                    ");
 if (totalUserPages > 1) { 
      out.write("\r\n");
      out.write("                    <div class=\"pagination\">\r\n");
      out.write("                        <div class=\"pagination-controls\">\r\n");
      out.write("\r\n");
      out.write("                            <!-- Seitenzahlen -->\r\n");
      out.write("                            <div class=\"page-numbers\">\r\n");
      out.write("                                ");
 
                                int userStartPage = Math.max(1, userPage - 1);
                                int userEndPage = Math.min(totalUserPages, userPage + 1);
                                
                                // Erste Seite falls nicht sichtbar
                                if (userStartPage > 1) { 
      out.write("\r\n");
      out.write("                                    <a href=\"admin_user.jsp?uid=");
      out.print( userAnzeigen.getUid() );
      out.write("&userPage=1\" class=\"page-number\">1</a>\r\n");
      out.write("                                    ");
 if (userStartPage > 2) { 
      out.write("\r\n");
      out.write("                                        <span class=\"page-dots\">...</span>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                ");
 }
                                
                                // Sichtbare Seitenzahlen
                                for (int i = userStartPage; i <= userEndPage; i++) { 
      out.write("\r\n");
      out.write("                                    ");
 if (i == userPage) { 
      out.write("\r\n");
      out.write("                                        <span class=\"page-number active\">");
      out.print( i );
      out.write("</span>\r\n");
      out.write("                                    ");
 } else { 
      out.write("\r\n");
      out.write("                                        <a href=\"admin_user.jsp?uid=");
      out.print( userAnzeigen.getUid() );
      out.write("&userPage=");
      out.print( i );
      out.write("\" class=\"page-number\">");
      out.print( i );
      out.write("</a>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                ");
 }
                                
                                // Letzte Seite falls nicht sichtbar
                                if (userEndPage < totalUserPages) { 
      out.write("\r\n");
      out.write("                                    ");
 if (userEndPage < totalUserPages - 1) { 
      out.write("\r\n");
      out.write("                                        <span class=\"page-dots\">...</span>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    <a href=\"admin_user.jsp?uid=");
      out.print( userAnzeigen.getUid() );
      out.write("&userPage=");
      out.print( totalUserPages );
      out.write("\" class=\"page-number\">");
      out.print( totalUserPages );
      out.write("</a>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"verlauf-table-container\">\r\n");
      out.write("                        <table class=\"verlauf-table\">\r\n");
      out.write("                            <caption>Transaktionsverlauf</caption>\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>Datum</th>\r\n");
      out.write("									<th>#</th>\r\n");
      out.write("                                    <th>Benutzer</th>\r\n");
      out.write("                                    <th>Summe</th>\r\n");
      out.write("                                    <th>Kommentar</th>\r\n");
      out.write("                                    <th>Inhalt</th>\r\n");
      out.write("                                    <th></th>\r\n");
      out.write("                                    <th></th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                ");

                                // Berechnung für aktuelle Seite
                                int userStartIndex = (userPage - 1) * userBuchungsPerPage;
                                int userEndIndex = Math.min(userStartIndex + userBuchungsPerPage, totalUserBuchungen);
                                
                                java.util.List<Buchung> userBuchungen = alleUserBuchungen.subList(userStartIndex, userEndIndex);
                                
                                for(Buchung buchung : userBuchungen) {
                                    String betrag = euroFormat.format(buchung.getSumme() / 100.0);
                                    String itemlist = Buchung.itemlistToString(buchung);
                                    String datum = dateFormat.format(buchung.getDatum());
									String buchungstyp = buchung.getBt().toString().toLowerCase();
                                
      out.write("\r\n");
      out.write("                                    <tr class=\"");
      out.print( buchungstyp );
      out.write("\">\r\n");
      out.write("                                        <td>");
      out.print( datum );
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print( buchung.getUid() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( userAnzeigen.getVorname() );
      out.write(' ');
      out.print( userAnzeigen.getNachname() );
      out.write("</td>\r\n");
      out.write("                                        <td class=\"betrag\">");
      out.print( betrag );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( buchung.getKommentar() != null ? buchung.getKommentar() : "-" );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( itemlist != null && !itemlist.trim().isEmpty() ? itemlist : "-" );
      out.write("</td>\r\n");
      out.write("                                         ");
 if(buchungstyp.equals("striche")) { 
      out.write("\r\n");
      out.write("                                        <td>\r\n");
      out.write("										<form action=\"buchungen\" method=\"post\">\r\n");
      out.write("      									<input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print(userAnzeigen.getUid());
      out.write("\">\r\n");
      out.write("     									<input type=\"hidden\" name=\"buchungID\" value=\"");
      out.print( buchung.getUid() );
      out.write("\">\r\n");
      out.write("       									<button type=\"submit\" name=\"method\" value=\"bearbeitenBuchung\" class=\"btn btn-edit \">Bearbeiten</button>\r\n");
      out.write("   									</form>\r\n");
      out.write("									</td>\r\n");
      out.write("									");
 } else { 
      out.write("\r\n");
      out.write("									<td>-</td>\r\n");
      out.write("									");
 } 
      out.write("\r\n");
      out.write("									<td>\r\n");
      out.write("										<form action=\"buchungen\" method=\"post\">\r\n");
      out.write("     									<input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print(userAnzeigen.getUid());
      out.write("\">\r\n");
      out.write("     									<input type=\"hidden\" name=\"buchungID\" value=\"");
      out.print( buchung.getUid() );
      out.write("\">\r\n");
      out.write("       									<button type=\"submit\" name=\"method\" value=\"loescheBuchung\" class=\"btn btn-danger\">Löschen</button>\r\n");
      out.write("   									</form>\r\n");
      out.write("									</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                ");
}
      out.write("\r\n");
      out.write("                          	</tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("			<div class=\"navigation\">\r\n");
      out.write("				<a href=\"verlauf.jsp\" class=\"btn btn-auswahl\">Verlauf</a>\r\n");
      out.write("				<a href=\"profil.jsp\" class=\"btn btn-auswahl\">Profil</a>\r\n");
      out.write("				");
 if(user.isAdmin()) { 
      out.write("\r\n");
      out.write("                        <a href=\"admin_item.jsp\" class=\"btn btn-auswahl\">Artikel</a>\r\n");
      out.write("                        <a href=\"admin_user.jsp\" class=\"btn btn-auswahl\">Benutzer und Buchungen</a>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- User Data for JavaScript -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var users = [];\r\n");
      out.write("        ");
 
        for (User u : myUsers) { 
        
      out.write("\r\n");
      out.write("            users.push({ \r\n");
      out.write("                name: '");
      out.print( u.getNachname() );
      out.write("', \r\n");
      out.write("                fname: '");
      out.print( u.getVorname() );
      out.write("', \r\n");
      out.write("                uid: '");
      out.print( u.getUid() );
      out.write("',\r\n");
      out.write("                active: ");
      out.print( u.isAktiv() );
      out.write(",\r\n");
      out.write("                admin: ");
      out.print( u.isAdmin() );
      out.write(",\r\n");
      out.write("                status: '");
      out.print( u.getStatus() );
      out.write("'\r\n");
      out.write("            });\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/admin.js\"></script>\r\n");
      out.write("    <script src=\"js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
