/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-10-01 11:50:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import de.uniwue.apps.jm1.User;
import de.uniwue.apps.jm1.Item;
import de.uniwue.apps.jm1.Main;
import de.uniwue.apps.jm1.Buchung;
import java.text.SimpleDateFormat;
import java.util.List;
import java.text.DecimalFormat;

public final class admin_005fitem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("de.uniwue.apps.jm1.Buchung");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.User");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.Item");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.Main");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User user = (User) session.getAttribute("user");
if (user == null || !user.isAdmin()) {
    response.sendRedirect("index.jsp");
    return;
}

user = User.getUserbyUID("" + user.getUid());
session.setAttribute("user", user);

// Item to display parameter handling
String uid = null;
Item itemAnzeigen = null;
try {
    uid = "" + Integer.parseInt(request.getParameter("uid"));
    itemAnzeigen = Item.getItem(Integer.parseInt(uid));
} catch(Exception e) {
    // uid bleibt null, itemAnzeigen bleibt null
}

// Formatierungen
DecimalFormat euroFormat = new DecimalFormat("#,##0.00 €");
SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm");
String adminGuthaben = euroFormat.format(user.getGuthaben() / 100.0);

List<Item> myItems = Item.getItLi();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"de\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Item-Verwaltung - WueKaStL</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/admin.css\">\r\n");
      out.write("    <script src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <div class=\"user-info-header\">\r\n");
      out.write("            <div class=\"user-name-header\">");
      out.print( user.getVorname() );
      out.write(' ');
      out.print( user.getNachname() );
      out.write("</div>\r\n");
      out.write("            <div class=\"saldo\">");
      out.print( adminGuthaben );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("         <a class=\"logo\" href=\"index.jsp\" >WueKaStL</a>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"index.jsp\" class=\"btn  btn-danger\" >zur Startseite</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Hauptbereich -->\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <h2 class=\"main-title\">Artikel</h2>\r\n");
      out.write("        ");
 if(itemAnzeigen == null) { 
      out.write("\r\n");
      out.write("        <!-- Navigation Buttons -->\r\n");
      out.write("        <div class=\"navigation\">\r\n");
      out.write("            <button id=\"neues-Item\" class=\"btn btn-auswahl\">\r\n");
      out.write("                Neuer Artikel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"user-navigation\">\r\n");
      out.write("        <div id=\"item-list-section\" class=\"list-container\">\r\n");
      out.write("            <div class=\"list-header\">\r\n");
      out.write("                <h3>Artikel auswählen</h3>\r\n");
      out.write("                <div class=\"search\">\r\n");
      out.write("                    <input type=\"text\" id=\"item-search-input\" placeholder=\"Item suchen...\" class=\"search-input\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Item Grid -->\r\n");
      out.write("            <div class=\"grid\" id=\"item-grid\">\r\n");
      out.write("                ");
 for(Item i : myItems) {
                    String statusClass = i.isAktiv() ? "active" : "inactive";
					String preis = euroFormat.format(i.getPreis() / 100.0);
                
      out.write("\r\n");
      out.write("                <div class=\"card\" data-uid=\"");
      out.print( i.getUid() );
      out.write("\">\r\n");
      out.write("                    <div class=\"name\">");
      out.print( i.getName() );
      out.write("</div>\r\n");
      out.write("                <div class=\"actions\">\r\n");
      out.write("                    <div class=\"info\">\r\n");
      out.write("                    <a style=\"font-weight: 500\">");
      out.print( preis );
      out.write("</a>\r\n");
      out.write("					<div class=\"status\">\r\n");
      out.write("                        <div class=\"badge ");
      out.print( statusClass );
      out.write("\"> </div>\r\n");
      out.write("                        <div class=\"id\">ID: ");
      out.print( i.getUid() );
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("					</div>\r\n");
      out.write("                    <div class=\"form-actions\">\r\n");
      out.write("                        <a href=\"admin_item.jsp?uid=");
      out.print( i.getUid() );
      out.write("\" class=\"btn btn-edit\">\r\n");
      out.write("                            Bearbeiten\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("				</div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Neues Item -->\r\n");
      out.write("        <div id=\"new-item-section\" class=\"list-container\" style=\"display: none; max-width: 400px;\"> \r\n");
      out.write("                    <div class=\"list-header\">\r\n");
      out.write("                        <h3>Neuer Artikel erstellen</h3>\r\n");
      out.write("                        <button class=\"btn btn-close\">✕</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <form id=\"new-item-form\" method=\"POST\" action=\"artikel\" class=\"admin-form\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"new-item-name\">Name *</label>\r\n");
      out.write("                            <input type=\"text\" id=\"new-item-name\" name=\"name\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"new-item-preis\">Preis (€) *</label>\r\n");
      out.write("                            <input type=\"number\" id=\"new-item-preis\" name=\"preis\" min=\"0\" step=\"0.01\" placeholder=\"0,00\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"new-item-datum\">Gültig ab *</label>\r\n");
      out.write("                            <input type=\"date\" id=\"new-item-datum\" name=\"datumAb\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-actions\">\r\n");
      out.write("                            <button type=\"submit\" name=\"method\" value=\"neues-item\" class=\"btn btn-edit\">\r\n");
      out.write("                                Artikel erstellen\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if(itemAnzeigen != null) { 
      out.write("\r\n");
      out.write("        <!-- Navigation Buttons -->\r\n");
      out.write("            <div class=\"navigation\">\r\n");
      out.write("            <a href=\"admin_item.jsp\" class=\"btn btn-auswahl\"> <i class=\"arrow left\"></i>  Zurück zur Artikelliste</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Anzeige Section -->\r\n");
      out.write("        <div class=\"Anzeige\">\r\n");
      out.write("            ");
 if(itemAnzeigen != null) { 
      out.write("\r\n");
      out.write("                <section class=\"item-einstellungen\">\r\n");
      out.write("                    <!-- Item Info -->\r\n");
      out.write("                    <div class=\"item-info-section\">\r\n");
      out.write("                        <div class=\"item-header\">\r\n");
      out.write("                            <h3>");
      out.print( itemAnzeigen.getName() );
      out.write("</h3>\r\n");
      out.write("                            <div class=\"item-status ");
      out.print( itemAnzeigen.isAktiv() ? "active" : "inactive" );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( itemAnzeigen.isAktiv() ? "Aktiv" : "Inaktiv" );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"item-details\">\r\n");
      out.write("                            <p><strong>Artikel-ID:</strong> ");
      out.print( itemAnzeigen.getUid() );
      out.write("</p>\r\n");
      out.write("                            <p><strong>Status:</strong> ");
      out.print( itemAnzeigen.isAktiv() ? "Verfügbar" : "Deaktiviert" );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Aktivierung/Deaktivierung -->\r\n");
      out.write("                        <form method=\"POST\" action=\"artikel\" class=\"status-form\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"");
      out.print(Main.ITEM_UID_PARAM);
      out.write("\" value=\"");
      out.print( itemAnzeigen.getUid() );
      out.write("\">\r\n");
      out.write("                            ");
 if(itemAnzeigen.isAktiv()) { 
      out.write("\r\n");
      out.write("                                <button type=\"submit\" name=\"method\" value=\"deaktivieren\" class=\"btn btn-danger\">\r\n");
      out.write("                                    Deaktivieren\r\n");
      out.write("                                </button>\r\n");
      out.write("                            ");
 } else { 
      out.write("\r\n");
      out.write("                                <button type=\"submit\" name=\"method\" value=\"aktivieren\" class=\"btn btn-success\">\r\n");
      out.write("                                    Aktivieren\r\n");
      out.write("                                </button>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Name ändern -->\r\n");
      out.write("                        <div class=\"name-bearbeiten\">\r\n");
      out.write("                            <h4>Name ändern</h4>\r\n");
      out.write("                            <form method=\"POST\" action=\"artikel\" class=\"admin-form\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"");
      out.print(Main.ITEM_UID_PARAM);
      out.write("\" value=\"");
      out.print( itemAnzeigen.getUid() );
      out.write("\">\r\n");
      out.write("                                <div class=\"form-row\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label>Name</label>\r\n");
      out.write("                                        <input name=\"name\" placeholder=\"");
      out.print( itemAnzeigen.getName() );
      out.write("\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"submit\" name=\"method\" value=\"name-change\" class=\"btn btn-edit\">Name ändern</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Preis Management -->\r\n");
      out.write("                    <div class=\"preis-section\">\r\n");
      out.write("                        <h4>Preis verwalten</h4>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Preisformular -->\r\n");
      out.write("                        <form method=\"POST\" action=\"artikel\" class=\"admin-form preis-form\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"");
      out.print(Main.ITEM_UID_PARAM);
      out.write("\" value=\"");
      out.print( itemAnzeigen.getUid() );
      out.write("\">\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"itemPreis\">Preis (€)</label>\r\n");
      out.write("                                <input type=\"number\" id=\"itemPreis\" name=\"preis\" min=\"0\" step=\"0.01\" placeholder=\"0,00\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"itemDatum\">Gültig ab</label>\r\n");
      out.write("                                <input type=\"date\" id=\"itemDatum\" name=\"datumAb\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <button type=\"submit\" name=\"method\" value=\"change-preis\" class=\"btn btn-edit\">\r\n");
      out.write("                               Preis ändern\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("			<div class=\"navigation\">\r\n");
      out.write("				<a href=\"verlauf.jsp\" class=\"btn btn-auswahl\">Verlauf</a>\r\n");
      out.write("				<a href=\"profil.jsp\" class=\"btn btn-auswahl\">Profil</a>\r\n");
      out.write("				");
 if(user.isAdmin()) { 
      out.write("\r\n");
      out.write("                        <a href=\"admin_item.jsp\" class=\"btn btn-auswahl\">Artikel</a>\r\n");
      out.write("                        <a href=\"admin_user.jsp\" class=\"btn btn-auswahl\">Benutzer und Buchungen</a>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- Item Data for JavaScript -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var items = [];\r\n");
      out.write("        ");
 
        for (Item i : myItems) { 
        
      out.write("\r\n");
      out.write("            items.push({ \r\n");
      out.write("                name: '");
      out.print( i.getName() );
      out.write("', \r\n");
      out.write("                uid: '");
      out.print( i.getUid() );
      out.write("',\r\n");
      out.write("                active: ");
      out.print( i.isAktiv() );
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(itemAnzeigen != null) { 
      out.write("\r\n");
      out.write("        var currentItem = {\r\n");
      out.write("            name: \"");
      out.print( itemAnzeigen.getName() );
      out.write("\",\r\n");
      out.write("            aktiv: ");
      out.print( itemAnzeigen.isAktiv() );
      out.write(",\r\n");
      out.write("            uid: \"");
      out.print( itemAnzeigen.getUid() );
      out.write("\"\r\n");
      out.write("        };\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/admin.js\"></script>\r\n");
      out.write("    <script src=\"js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
