/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-10-14 10:41:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import de.uniwue.apps.jm1.User;
import de.uniwue.apps.jm1.Item;
import de.uniwue.apps.jm1.Main;
import java.text.DecimalFormat;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.User");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.Item");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.Main");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"exception.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

User user = (User) session.getAttribute("user");
if (user == null) {
    response.sendRedirect("benutzer.jsp");
    return;
}
user = User.getUserbyUID("" + user.getUid());
session.setAttribute("user", user);

int isSuccess = 0;
try {
    isSuccess = Integer.parseInt(request.getParameter("isSuccess"));
} catch(Exception e) {
    // positiv bleibt null
}

DecimalFormat euroFormat = new DecimalFormat("#,##0.00 €");
String guthaben = euroFormat.format(user.getGuthaben() / 100.0);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"de\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>WueKaStL</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <script src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <div class=\"user-info-header\">\r\n");
      out.write("            <div class=\"user-name-header\">");
      out.print( user.getVorname() );
      out.write(' ');
      out.print( user.getNachname() );
      out.write("</div>\r\n");
      out.write("            <div class=\"saldo\">");
      out.print( guthaben );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("         <a class=\"logo\" href=\"index.jsp\" >WueKaStL</a>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("             <a href=\"auth/abmeldung\" class=\"btn btn-danger\">Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Hauptbereich -->\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <h2 class=\"main-title\">Getränk auswählen</h2>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"content-container\">\r\n");
      out.write("            <div class=\"drinks-section\">\r\n");
      out.write("                <div class=\"drinks-grid\">\r\n");
      out.write("                    ");
 
                    for (Item item : Item.getItLi()) {
                        if (item.isAktiv()) {
                            String preis;
                            int preisInCent = item.getPreis();
                            if (preisInCent >= 100) {
                                preis = euroFormat.format(preisInCent / 100.0);
                            } else {
                                preis = preisInCent + " ct";
                            }
                    
      out.write("\r\n");
      out.write("                        <div class=\"drink-card add-item\" \r\n");
      out.write("                             data-uid=\"");
      out.print( item.getUid() );
      out.write("\" \r\n");
      out.write("                             data-itempreis-id=\"");
      out.print( item.getItempreisID() );
      out.write("\"\r\n");
      out.write("                             data-name=\"");
      out.print( item.getName() );
      out.write("\"\r\n");
      out.write("                             data-price=\"");
      out.print( preisInCent );
      out.write("\">\r\n");
      out.write("                            <div class=\"drink-name\">");
      out.print( item.getName() );
      out.write("</div>\r\n");
      out.write("                            <img alt=\"");
      out.print( item.getName() );
      out.write("\" class=\"icon-img\" src=\"");
      out.print( item.getIconUrl() );
      out.write("\">\r\n");
      out.write("                            <div class=\"drink-price\">");
      out.print( preis );
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 
                        }
                    } 
                    
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"warenkorb-box\">\r\n");
      out.write("                <h3>Warenkorb</h3>\r\n");
      out.write("                <ul class=\"warenkorb\" id=\"warenkorb-liste\">\r\n");
      out.write("         \r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"warenkorb-summe\">\r\n");
      out.write("                    <span class=\"sum-label\">Gesamtsumme:</span>\r\n");
      out.write("                    <div class=\"sum-actions\">\r\n");
      out.write("                        <span class=\"sum-value\">\r\n");
      out.write("                            0<span class=\"euro\">€</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <form action=\"buchungen\" id=\"warenkorb-form\" method=\"POST\" style=\"display: inline;\">\r\n");
      out.write("                            <button type=\"submit\" class=\"bestaetigen\" name=\"method\" value=\"strich\" disabled>\r\n");
      out.write("                                Bestätigen\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("			");
if(isSuccess == 1){ 
      out.write("\r\n");
      out.write("			<div class=\"success\">\r\n");
      out.write("    		<div class=\"success__title\">Hat alles funktioniert ;D</div>\r\n");
      out.write("    		<div class=\"success__close\"><svg  width=\"20\" viewBox=\"0 0 20 20\" height=\"20\"><path fill=\"#393a37\" d=\"m15.8333 5.34166-1.175-1.175-4.6583 4.65834-4.65833-4.65834-1.175 1.175 4.65833 4.65834-4.65833 4.6583 1.175 1.175 4.65833-4.6583 4.6583 4.6583 1.175-1.175-4.6583-4.6583z\"></path></svg></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("			<div class=\"navigation\">\r\n");
      out.write("				<a href=\"verlauf.jsp\" class=\"btn btn-auswahl\">Verlauf</a>\r\n");
      out.write("				<a href=\"profil.jsp\" class=\"btn btn-auswahl\">Profil</a>\r\n");
      out.write("				");
 if(user.isAdmin()) { 
      out.write("\r\n");
      out.write("                        <a href=\"admin_item.jsp\" class=\"btn btn-auswahl admin-nav\">Artikel</a>\r\n");
      out.write("                        <a href=\"admin_user.jsp\" class=\"btn btn-auswahl admin-nav\">Benutzer und Buchungen</a>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
