/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-10-01 11:51:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import de.uniwue.apps.jm1.User;
import de.uniwue.apps.jm1.Item;
import de.uniwue.apps.jm1.Main;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

public final class profil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.User");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.Item");
    _jspx_imports_classes.add("de.uniwue.apps.jm1.Main");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
    User user = (User) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect("benutzer.jsp");
    }else{
    	user = User.getUserbyUID("" + user.getUid());
    	session.setAttribute("user", user);
    	
    	DecimalFormat euroFormat = new DecimalFormat("#,##0.00 €");
    	SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy HH:mm");
    	String Guthaben = euroFormat.format(user.getGuthaben() / 100.0);    
    	
    	
    	boolean neuerPin = false;
    	try {
    	    neuerPin = "true".equals(request.getParameter("neuerPin"));
    	} catch(Exception e) {
    	    throw new Exception("Bei der Änderung deines Pin ist ein Fehler aufgetretten");
    	}

      out.write("\r\n");
      out.write("<!-- Index.html -->\r\n");
      out.write("<html lang=\"de\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>WueKaStL</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("  <script src=\"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Header -->\r\n");
      out.write("  <div class=\"header\">\r\n");
      out.write("        <div class=\"user-info-header\">\r\n");
      out.write("            <div class=\"user-name-header\">");
      out.print( user.getVorname() );
      out.write(' ');
      out.print( user.getNachname() );
      out.write("</div>\r\n");
      out.write("            <div class=\"saldo\">");
      out.print( Guthaben );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <a class=\"logo\" href=\"index.jsp\" >WueKaStL</a>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"index.jsp\" class=\"btn  btn-danger\" ><i class=\"arrow left\"></i>zur Startseite</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Hauptbereich -->\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("	<!-- Profil Menü -->\r\n");
      out.write("	<div class=\"navigation\">\r\n");
      out.write("		");
 if(User.userHatPin(user) && !user.isAdmin()) { 
      out.write("\r\n");
      out.write("		<form method=\"POST\" action=\"benutzer\" class=\"admin-form\">\r\n");
      out.write("		<input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print(user.getUid());
      out.write("\">\r\n");
      out.write("		<input type=\"hidden\" name=\"profil\" value=\"true\">\r\n");
      out.write("		<input name=\"pin\"  type=\"hidden\" >\r\n");
      out.write("		<button id=\"Pin-deaktivieren\" class=\"btn btn-danger\">Pin deaktivieren</button>\r\n");
      out.write("		</form>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Profil Anzeige   -->\r\n");
      out.write("	<div class=\"Anzeige\">\r\n");
      out.write("		<div class=\"user-info-section\">\r\n");
      out.write("			<div class=\"user-header\">\r\n");
      out.write("                            <h3>");
      out.print( user.getVorname() );
      out.write(' ');
      out.print( user.getNachname() );
      out.write("</h3>\r\n");
      out.write("                            <div class=\"user-status ");
      out.print( user.isAktiv() ? "active" : "inactive" );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( user.isAktiv() ? "Aktiv" : "Inaktiv" );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"user-details\">\r\n");
      out.write("                            <p><strong>Status:</strong> ");
      out.print( user.getStatus() );
      out.write("</p>\r\n");
      out.write("                            <p><strong>Guthaben:</strong> <span class=\"balance\">");
      out.print( Guthaben );
      out.write("</span></p>\r\n");
      out.write("                            <p><strong>Admin:</strong> ");
      out.print( user.isAdmin() ? "Ja" : "Nein" );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
if(!user.isAdmin()) {
      out.write("\r\n");
      out.write("						<div class=\"neuer-pin\">\r\n");
      out.write("                            <h4>PIN </h4>\r\n");
      out.write("                            <form method=\"POST\" id=\"pinÄnderung\" action=\"benutzer\" class=\"admin-form\">\r\n");
      out.write("                            	<p>Bitte nur Ziffern eingeben</p>\r\n");
      out.write("                                <input type=\"hidden\" name=\"");
      out.print(Main.USER_UID_PARAM);
      out.write("\" value=\"");
      out.print(user.getUid());
      out.write("\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"profil\" value=\"true\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <input name=\"pin\"  pattern=\"[0-9]+\" id=\"pin\" type=\"password\" placeholder=\"Neuen PIN\" minlength=\"4\" maxlength=\"10\" class=\"pin-eingabe\" required >\r\n");
      out.write("                                    <input name=\"pin_confirm\"  pattern=\"[0-9]+\" id=\"pin_confirm\" type=\"password\" placeholder=\"Neuen PIN bestätigen\" minlength=\"4\" maxlength=\"10\" class=\"pin-eingabe\" required >\r\n");
      out.write("                                    ");
 if (User.userHatPin(user)){ 
      out.write("\r\n");
      out.write("                                    <button type=\"submit\" name=\"method\" value=\"pin-change\" class=\"btn btn-edit\">PIN ändern</button>\r\n");
      out.write("                                    ");
 } else{ 
      out.write("\r\n");
      out.write("                                    <button type=\"submit\" name=\"method\" value=\"pin-change\" class=\"btn btn-edit\">PIN setzen</button>\r\n");
      out.write("                                	");
 } 
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } else{
      out.write("\r\n");
      out.write("                        <div class=\"neuer-pin\">\r\n");
      out.write("                        	<h4>Als Admin PIN bitte in der Benutzerverwaltung am PC ändern</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
 if(neuerPin){ 
      out.write("\r\n");
      out.write("	<div class=\"success\">\r\n");
      out.write("    		<div class=\"success__title\">Hat alles funktioniert ;D</div>\r\n");
      out.write("    		<div class=\"success__close\"><svg  width=\"20\" viewBox=\"0 0 20 20\" height=\"20\"><path fill=\"#393a37\" d=\"m15.8333 5.34166-1.175-1.175-4.6583 4.65834-4.65833-4.65834-1.175 1.175 4.65833 4.65834-4.65833 4.6583 1.175 1.175 4.65833-4.6583 4.6583 4.6583 1.175-1.175-4.6583-4.6583z\"></path></svg></div>\r\n");
      out.write("			\r\n");
      out.write("	</div>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer -->\r\n");
      out.write("  <div class=\"footer\">\r\n");
      out.write("    <div class=\"navigation\">\r\n");
      out.write("				<a href=\"verlauf.jsp\" class=\"btn btn-auswahl\">Verlauf</a>\r\n");
      out.write("				<a href=\"profil.jsp\" class=\"btn btn-auswahl active\">Profil</a>\r\n");
      out.write("				");
 if(user.isAdmin()) { 
      out.write("\r\n");
      out.write("                        <a href=\"admin_item.jsp\" class=\"btn btn-auswahl admin-nav\">Artikel</a>\r\n");
      out.write("                        <a href=\"admin_user.jsp\" class=\"btn btn-auswahl admin-nav\">Benutzer und Buchungen</a>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.getElementById(\"pinÄnderung\").onsubmit = function () {\r\n");
      out.write("  var pw1 = document.getElementById(\"pin\").value;\r\n");
      out.write("  var pw2 = document.getElementById(\"pin_confirm\").value;\r\n");
      out.write("  if (pw1 !== pw2) {\r\n");
      out.write("    alert(\"Die Passwörter stimmen nicht überein!\");\r\n");
      out.write("    return false; // das Formular wird NICHT abgesendet\r\n");
      out.write("  }\r\n");
      out.write("  return true;\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
 } 
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
